name: main

env:
  CI: true
on:
  push:
    branches:
      - master

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
      tag-name: v${{ steps.package-version.outputs.version }}
      is-pre-version: ${{ steps.pre-version.outputs.is-pre-version }}
      tag-exist: ${{ steps.tag-exist.outputs.exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"

      - name: Set package version
        id: package-version
        run: node -p -e '`version=${require("./package.json").version}`' >> $GITHUB_OUTPUT

      - name: Check pre-release
        id: pre-version
        run: node -p -e '`is-pre-version=${require("./package.json").version.includes("-pre")}`' >> $GITHUB_OUTPUT

      - name: Check tag exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: tag-exist
        with:
          tag: v${{ steps.package-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: publish
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.tag-exist != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      # - name: Install
      #   run: npm ci
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build
      #   run: npm run build
      # まだpublishされていないバージョンならpublishする

      - name: Publish
        run: |
          npx can-npm-publish --verbose && npm publish || echo "Does not publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.setup.outputs.version }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.setup.outputs.tag-name }}
          name: Release ${{ needs.setup.outputs.tag-name }}
          body: ${{ steps.tag_version.outputs.changelog }}
          prerelease: ${{ needs.setup.outputs.is-pre-version }}
